### ISSUE TITLE
[요청사항1] 코딩시작 시 이동거리, 회전각도 기본값으로 초기화

### ISSUE THREAD

**Issue by HhanGgun** [BYROBOT/drone8#1]
현재 이동거리와 이동각도가 마지막에 설정한 값으로 저장되는데, 코딩시작을 할 때마다(코딩시작 카드를 읽을 때) 기본값(이동거리=1m, 회전각도=90도)으로 초기화되면 좋을 것 같습니다.

**Comment by realwolf** [comment]
매번 시작할 때마다 초기화하도록 수정하였습니다.
