### ISSUE TITLE
[엔트리] 회전 명령 블록 오류

### ISSUE THREAD

**Issue by HhanGgun** [BYROBOT/drone8#10]
아래와 같이 회전 명령 블록을 사용하면 회전하자마자 착륙하는 현상이 발생합니다. 회전 명령 블록이 실행되고 바로 다음 블록으로 넘어가는것 같습니다.

![image](https://user-images.githubusercontent.com/42791314/86990853-8e235b80-c1d8-11ea-8284-1abe287c1b9f.png)

**Comment by realwolf** [comment]
https://github.com/entrylabs/entryjs/pull/1900
회전 블록에서 시간 지연이 안되는 원인을 확인하여 수정했습니다.
반영은 빠르면 12월에 될 것으로 예상하고 있습니다.

**Comment by HhanGgun** [comment]
엔트리 온라인 버전에서 정상적으로 동작하는것 확인하였습니다.
오프라인 버전은 11월 26일에 업데이트(버전 2.0.30) 되었는데 아직 반영이 안되었습니다.

**Comment by realwolf** [comment]
@HhanGgun 오프라인 버전은 1달 가량 더 늦게 업데이트 하는 것으로 알고 있습니다.

**Comment by HhanGgun** [comment]
해당 이슈 오프라인 버전에서도 정상적으로 수정된 것 확인하였습니다. 감사합니다.
