### ISSUE TITLE
FHSS 기능 오류

### ISSUE THREAD

**Issue by HhanGgun** [BYROBOT/drone8#15]
스마트 조종기를 일반 충전 케이블에 연결한 후 케이블을 제거하면 FHSS 기능이 자동으로 켜지는 현상이 발생합니다.

**Comment by realwolf** [comment]
RF를 초기화 할 때 FHSS를 켜는 오류가 있었습니다.
최근 버젼에서 수정하였습니다.
http://dev.byrobot.co.kr/documents/kr/products/e_drone/log/updates/firmware/#heading-20201022

**Comment by HhanGgun** [comment]
FHSS가 자동으로 켜지는 현상은 수정되었으나, 설정 메뉴에서 FHSS 기능이 잘 꺼지지 않는 오류가 발생합니다.

**Comment by HhanGgun** [comment]
20.11.3 버전에서 FHSS 기능 정상 동작 확인하였습니다. 감사합니다.
