### ISSUE TITLE
드론/조종기 LED 기능 오류

### ISSUE THREAD

**Issue by HhanGgun** [BYROBOT/drone8#17]
드론과 조종기에서 다음과 같은 LED 오류가 발생합니다.

- 드론: 조종기의 설정 메뉴의 "LIGHT" 기능 동작하지 않음. R1 버튼만 LED 변경 가능함.
- 조종기: 조종기 LED 켜지지 않음(전원 켤때부터). 설정 메뉴의 "LIGHT" 기능도 동작하지 않음.

**Comment by realwolf** [comment]
http://dev.byrobot.co.kr/documents/kr/products/e_drone/log/updates/firmware/#heading-20201221
조종기 펌웨어를 업데이트하여 위의 두 문제를 수정하였습니다. 확인 부탁드립니다.

**Comment by HhanGgun** [comment]
펌웨어 업데이트하여 테스트한 결과, 정상적으로 수정된 것 확인하였습니다. 감사합니다.
