### ISSUE TITLE
[엔트리] 실시간 센서값 모니터링 창의 블록 이름 변경 요청

### ISSUE THREAD

**Issue by HhanGgun** [BYROBOT/drone8#18]
현재 엔트리의 실시간 센서값 모니터링 창의 블록 이름들이 영문으로 되어 있는데(엔트리 언어 설정 상관없이), 엔트리에서 설정한 언어로 표시되도록 수정 요청드립니다.
만약, 엔트리에서 설정한 언어로 표시하는 것이 불가능하다면 한글로 표시되도록 부탁드립니다.
블록 이름은 하드웨어 블록 상의 이름과 동일하게 해주시면 됩니다.

![image](https://user-images.githubusercontent.com/42791314/99490719-be141400-29ad-11eb-9e24-701ee021a8d2.png)

**Comment by realwolf** [comment]
테스트 해보니 언어에 대한 정의가 먼저 나온 후에 참조를 해야 정상적으로 표시되는 것을 확인하였습니다.
다음 업데이트에서는 정상적으로 표시되도록 수정하였습니다.

**Comment by HhanGgun** [comment]
온라인 버전에서는 정상적으로 수정된 것 확인하였습니다.
오프라인 버전도 업데이트되는대로 확인해보겠습니다.

**Comment by HhanGgun** [comment]
2021-02-26에 배포된 오프라인 v2.0.32에서 정상적으로 수정된 것 확인하였습니다. 감사합니다.
