### ISSUE TITLE
[엔트리] 블록 오류

### ISSUE THREAD

**Issue by HhanGgun** [BYROBOT/drone8#19]
엔트리 아래 블록에서 전후, 좌우, 상승/하강 조건에 모두 0을 입력한 후 회전 명령만 주면, 블록이 실행되자마자 바로 다음 블록으로 넘어가서 회전이 정상적으로 되지 않습니다. 
전후, 좌우, 상승/하강 조건에 어느 하나라도 0이 아닌 수를 입력하면 정상적으로 동작합니다.

![image](https://user-images.githubusercontent.com/42791314/100562449-22649b00-32ff-11eb-8506-18022ed4e66e.png)

**Comment by realwolf** [comment]
속도 값이 0일 때 0인지 확인하지 않고 (거리 / 속도)를 계산하는 수식이 있어서 문제를 일으킨 것으로 보입니다.
현재는 나누기 계산 전에 0인지 확인하도록 변경하였습니다.

**Comment by HhanGgun** [comment]
온라인 버전에서는 정상적으로 수정된 것 확인하였습니다.
오프라인 버전도 업데이트되는대로 확인해보겠습니다.

**Comment by HhanGgun** [comment]
2021-02-26에 배포된 오프라인 v2.0.32에서 정상적으로 수정된 것 확인하였습니다. 감사합니다.
