### ISSUE TITLE
[요청사항2] 착륙 카드를 읽지 않았을 때 자동으로 착륙하는 기능 추가

### ISSUE THREAD

**Issue by HhanGgun** [BYROBOT/drone8#2]
착륙 카드를 읽지 않고 코딩 실행을 한 경우, 모든 명령어 수행 후 약 5초 뒤 자동으로 착륙하는 기능을 추가하면 좋을 것 같습니다.
호버링도 생각해보았으나 호버링을 하게 되면 조종기가 없을 때 드론을 착륙시킬 방법이 없어서 어려울 것 같습니다.

**Comment by realwolf** [comment]
카드 코딩 종료 카드를 만났을 때 드론 비행 제어기가 대기 상태가 아니면 착륙 명령을 내리도록 수정하였습니다.
