### ISSUE TITLE
[언플러그드 모드] 비행모드/헤드리스모드 초기화 설정

### ISSUE THREAD

**Issue by HhanGgun** [BYROBOT/drone8#22]
조종기로 드론을 사용하다가 비행 모드(Attitude/Position)와 헤드리스 모드를 변경한 후 언플러그드 모드로 전환하면 해당 설정이 그대로 유지됩니다. 언플러그드 모드에서는 Attitude 모드와 헤드리스 모드를 사용하면 사고 발생 위험이 있고, 필요하지 않은 기능이라 판단되어 다음과 같이 수정 요청드립니다.

언플러그드 모드(카드코딩/모션코딩)로 설정하거나 전환 시 비행모드와 헤드리스 모드를 다음과 같이 초기화합니다.
- 비행 모드 : Position
- 헤드리스 모드: Normal(Headless X)

**Comment by realwolf** [comment]
21.2.1 버전에서 수정하였습니다.
http://dev.byrobot.co.kr/documents/kr/products/coding_drone/log/updates/firmware/#heading-202129

**Comment by HhanGgun** [comment]
수정해주신 부분 정상 동작 확인하였습니다. 감사합니다.
