### ISSUE TITLE
리셋 버튼으로 모드 전환 시 부저음 추가 요청

### ISSUE THREAD

**Issue by HhanGgun** [BYROBOT/drone8#23]
현재 리셋 버튼을 눌러서 모드를 전환시킬 수 있는데 부저음이 울리지 않아서 인지하기가 좀 힘든 점이 있습니다.
코딩카처럼 코딩드론도 부저음이 같이 울리도록 수정 부탁드립니다. 음은 각 모드별 설정음으로 해주시면 될 것 같습니다.

- 2번 눌렀을 때: 카드코딩 모드
- 3번 눌렀을 때: 모션코딩 모드
- 4번 눌렀을 때: 피아노 모드

**Comment by realwolf** [comment]
21.2.2 버전에서 수정했습니다.

**Comment by HhanGgun** [comment]
21.2.2 버전에서 정상 동작 확인하였습니다. 감사합니다.
