### ISSUE TITLE
[요청사항3] 이동 명령 후 1~2초 정도 호버링 시간 추가

### ISSUE THREAD

**Issue by HhanGgun** [BYROBOT/drone8#3]
**[As-is]**
현재 이동 명령 후 "1초 기다림" 명령을 사용하지 않고 바로 다른 이동 명령을 주면, 드론이 많이 흔들리면서 불안정하게 비행합니다. ex) 전진 후 바로 좌로 이동처럼 방향을 바꿀 때
그래서 카드코딩에서는 이동 명령어 다음에 "1초 기다림"을 사용하여 호버링 할 수 있는 시간을 주는데 "1초 기다림"을 매번 읽기가 힘듭니다. 또한, 모션코딩에서는 "1초 기다림" 명령을 줄 수 없습니다.

**[To-be]**
모든 이동 명령(전진, 후진, 왼쪽, 오른쪽, 상승, 하강, 좌회전, 우회전)이 끝난 후에 1~2초 정도 호버링 할 수 있는 시간을 주어 안정적으로 비행할 수 있도록 하면 좋을 것 같습니다. (이륙 명령 후에는 호버링 시간이 있는 것 같습니다.)

**Comment by realwolf** [comment]
이동 및 회전 시 기다리는 시간을 가변으로 추가하였습니다.
- 이동 후 이동 거리에 따라 최소 2.4초에서 최대 4.8초 동안 호버링합니다.
- 회전 후 회전 각도에 따라 최소 1.2초에서 최대 3.6초 동안 호버링합니다.
