### ISSUE TITLE
[요청사항4] 이동 거리와 회전 각도를 누적하여 한 번에 이동하도록 변경

### ISSUE THREAD

**Issue by HhanGgun** [BYROBOT/drone8#4]
**[As-is]**
예를 들어, 전진 명령을 3번 연속으로 주면 3m를 한 번에 이동하는 것이 아니라 1m 이동 후 잠시 멈췄다가 다시 1m 이동하는 식으로 실행됩니다.

**[To-be]**
이동 명령을 연속으로 또는 반복하여 주는 경우, 해당 거리 또는 각도를 누적하여 한 번에 이동/회전할 수 있게 해주면 좋을 것 같습니다. 만약, 1번씩 끊어서 실행하고 싶으면 중간에 "1초 기다림" 명령어를 사용하면 되므로 문제없을 것 같습니다. (카드코딩과 모션코딩 동일하게 적용)

**Comment by realwolf** [comment]
카드 코딩 및 모션 코딩에서 모두 동일한 카드가 연속으로 등장할 때 
해당 카드의 수를 카운트하여 그만큼의 이동 또는 회전을 한 번에 실행하도록 변경하였습니다.
