### ISSUE TITLE
[요청사항5] 코딩(카드, 모션) 종료 시 부저음이 나지 않습니다

### ISSUE THREAD

**Issue by HhanGgun** [BYROBOT/drone8#5]
카드코딩과 모션코딩에서 착륙 명령을 뺀 상태에서 실행이 끝나면 종료 부저음이 울리지 않습니다. 수정 부탁드립니다.

**Comment by realwolf** [comment]
2020.7.17 최근 버젼에서 테스트 했을 때 카드 코딩 종료 시에는 종료음이 나오나 모션 코딩 종료 시에는 종료음이 나오지 않는다고 함

**Comment by HhanGgun** [comment]
모션 코딩 종료 시에 종료음이 나오지 않습니다. 확인 부탁드립니다.

**Comment by realwolf** [comment]
http://dev.byrobot.co.kr/documents/kr/products/coding_drone/log/updates/firmware/#heading-20201013
위의 버전에서 수정하였습니다.

**Comment by HhanGgun** [comment]
수정해주신 버전으로 정상 동작 확인하였습니다. 감사합니다.
